project:
  name: prestashop
  regions:
    - eu-west-1
  shorten_stack_name: true
tests:
  prestashop:
    template: templates/production_ready_prestashop.yaml
    parameters:
      StackUUID: $[taskcat_genpass_5]
      DatabasePassword: $[taskcat_genpass_8]
      NestedStacksS3URL: https://production-ready-prestashop-cloudformation-template.s3.eu-west-1.amazonaws.com/versions/latest
